### ISSUE TITLE
Reading RSSI After Connecting to Bean

### ISSUE THREAD

**Issue by DanChesher** [PunchThrough/bean-sdk-android#24]
The Android API provides methods for reading the RSSI value after connecting to a BLE device: [BluetoothGatt.readRemoteRssi()](http://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#readRemoteRssi%28%29) and [BluetoothGattCallback.onReadRemoteRssi(android.bluetooth.BluetoothGatt, int, int)](http://developer.android.com/reference/android/bluetooth/BluetoothGattCallback.html#onReadRemoteRssi%28android.bluetooth.BluetoothGatt,%20int,%20int%29). The Bean API wraps these classes, but does not provide a way to initiate the RSSI read or retrieve the RSSI value from the callback. 

I've updated the Bean class to provide a method to initiate the RSSI read and updated the BeanListener class to provide a callback method to return the RSSI value. I've also updated the TestBeanAdvanced class to test these changes and verified that the test passes. If possible, I would like to share these changes so that they can be merged back into the master branch to be included in a release version of the Bean SDK. This is my first time using Git and I'm not sure how to go about sharing the changes. Is this something that people would like to see included in the Bean SDK? If so, any advice on how to share the changes? Thanks!

**Comment by swstack** [comment]
Hey @DanChesher , thanks for using and contributing to the Bean SDK, we really appreciate it! If you could, please open a pull request with your changes so that they can be reviewed and merged.

To get started, read this tutorial about [forking and using pull requests](https://help.github.com/articles/using-pull-requests/).

Thanks again!

**Comment by DanChesher** [comment]
@swstack thanks for the link to the tutorial! I followed the instructions there to create a fork, commit my changes to the fork, and then create a pull request. Please let me know if you see any issues. Thanks!

**Comment by swstack** [comment]
I will close this issue once the new version is released to Maven.

**Comment by MMIX2009** [comment]
@DanChesher can you please provide a code snippet that shows how the RSSI API works? I am getting the following error in Android Studio when I run my app: java.lang.NoSuchMethodError: No virtual method readRemoteRssi()V in class Lcom/punchthrough/bean/sdk/Bean;

I am using the following in onConnected():

 if(b!=null){
                b.readRemoteRssi();
            }

and expecting the result in onReadRemoteRssi(int rssi)

**Comment by swstack** [comment]
@MMIX2009 make sure you are using version `2.0.0` or above.

**Comment by MMIX2009** [comment]
@swstack: thanks for your reply. I made sure the version is correct. Now, I the code is stopping with no visible errors.

Do you have complete working code posted anywhere I can review?
Thanks,

**Comment by swstack** [comment]
`sdk/src/androidTest/java/com/punchthrough/bean/sdk/TestBeanAdvanced.java`
