### ISSUE TITLE
BroadcastReceiver﹕ BroadcastReceiver trying to return result during a non-ordered broadcast

### ISSUE THREAD

**Issue by AinaSG** [PunchThrough/bean-sdk-android#26]
Hi! I'm very new to the bean, so I'm trying the examples here. But not even the one listening to nearby beans works for me. This one https://github.com/PunchThrough/bean-sdk-android#list-nearby-beans

My problem is that "BeanManager.getInstance().startDiscovery(listener);" makes the app stop with a "BroadcastReceiver﹕ BroadcastReceiver trying to return result during a non-ordered broadcast" error.

I found this on the new, but I have no idea how to solve it: http://stackoverflow.com/questions/30568625/broadcastreceiver-trying-to-return-result-during-a-non-ordered-broadcast-weird-e

Here's my main activity: https://gist.github.com/AinaSG/6546cb652f6cce6583ba554d34a8eb99

Sorry if this is not a real issue. Thanks for your help.

**Comment by AinaSG** [comment]
Ok, so I did some experiments and I think the issue is caused by running the app in an emulated device. Sorry for everything.

**Comment by swstack** [comment]
Hi @AinaSG. Thanks for submitting a ticket. I have not done much testing of BLE tests on the Android emulator, I typically use a connected device. Let me know if you need any more assistance!
