### ISSUE TITLE
Can BeanManager only be used in UI thread?

### ISSUE THREAD

**Issue by pbauermeister** [PunchThrough/bean-sdk-android#7]
I am trying to start a discovery (`BeanManager.getInstance().startDiscovery()`) from a background thread, but it throws an exception. 
Do you confirm that it only works inside the main (UI) thread?

Thank you!
-- Pascal

**Comment by swstack** [comment]
Hi @pbauermeister I am very sorry for the delayed response!  I am working to reproduce this and *might* be on to something but in the meantime please provide me with any additional information such as:

* How is it failing? (e.g. quits unexpectedly, etc)
* Do you have logcat logs of when it fails?
* How exactly are you setting up your background thread? (e.g. `AsyncTask`? `Thread`?)

I will get back to you shortly.

**Comment by swstack** [comment]
Unfortunately I am not able to reproduce the failure in all cases, although I have seen it fail in one occasion...please provide the information requested above along with a code snippet if possible!
